# -*- coding: utf-8 -*-
"""Case financeiro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DRaeIYjmm8H-0W4Hc8aSwZOz6rlABjl
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

#importando a base
df = pd.read_excel('/content/Vase_004 - Magalu - Sem Resolução.xlsx')

#analisando os primeiros registros
df.head()

#tamanho da base
df.shape

#informações sobre a abase de dados
df.info()

#transformando a coluna data como index da base
data = df.set_index('Data')

data.head()

plt.style.use('seaborn-darkgrid')
plt.figure(figsize=(16,5))
plt.title('Analise do fechamento', fontsize=14, loc='left')
plt.plot(data.index, data['Fechamento']);

plt.xlabel('Periodo da Cotação')
plt.ylabel('Valor da Ação R$');

#verificando os ultimos registros da base e os ultimos valores de fechamento das ações
data.tail()

media_movel = data['Fechamento'].rolling(5).mean()
media_tendencia = data['Fechamento'].rolling(30).mean()

plt.style.use('seaborn-darkgrid')
plt.figure(figsize=(16,5))
plt.title('Analise do fechamento', fontsize=14, loc='left')


plt.plot(data.index, data['Fechamento'])
plt.plot(data.index, media_movel)
plt.plot(data.index, media_tendencia)

plt.xlabel('Periodo da Cotação')
plt.ylabel('Valor da Ação R$');

df['Mes']= df['Data'].dt.month

df.head()

#Analisando a media de fechamento em cada mês
plt.figure( figsize=(15,6) )
sns.boxplot( data=df, x='Mes', y='Fechamento');

df.groupby(['Mes']).describe()['Fechamento']

graph = go.Figure(
    data=[
        go.Candlestick(
            x= data.index,
            open = data['Abertura'],
            high = data['Maior'],
            low = data['Menor'],
            close = data['Fechamento']
        )
    ]
)

graph.update_layout( xaxis_rangeslider_visible=False )

graph.show()
